/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kreditku.anto.ui;

import com.kreditku.anto.dao.BarangDao;
import com.kreditku.anto.model.Barang;
import com.mirzaakhena.swing.basetablemodel.BaseTableModel;
import java.awt.HeadlessException;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author antosamalona
 */
public class BarangUi extends javax.swing.JInternalFrame {

    private BarangDao barangDao;
    private BaseTableModel<Barang> tableModel;
    
    
    public BarangUi() {
        initComponents();
        tableModel = new BaseTableModel<Barang>() {};
            tblBrg.setModel(tableModel);
            barangDao = BarangDao.getBarangDao();
            List<Barang> listBarang = barangDao.getAll();
            tableModel.setItem(listBarang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEdit = new javax.swing.JButton();
        jSimpan = new javax.swing.JButton();
        jHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKdBarang = new javax.swing.JTextField();
        txtNmBarang = new javax.swing.JTextField();
        txtHrgBarang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBrg = new javax.swing.JTable();

        setClosable(true);
        setTitle("Data Barang");
        setName(""); // NOI18N

        jEdit.setText("Edit");
        jEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditActionPerformed(evt);
            }
        });

        jSimpan.setText("Simpan");
        jSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSimpanActionPerformed(evt);
            }
        });

        jHapus.setText("Hapus");
        jHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHapusActionPerformed(evt);
            }
        });

        jLabel1.setText("Kode Barang");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Harga Barang");

        tblBrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBrgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBrg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHrgBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNmBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNmBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHrgBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEdit)
                            .addComponent(jSimpan)
                            .addComponent(jHapus))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSimpanActionPerformed
        
        try {
            
            //KoneksiDb.connection.setAutoCommit(false);
           // barangDao = BarangDao.getBarangDao();
            
             if(txtKdBarang.getText().length()==0){
                            JOptionPane.showMessageDialog(this, "data tidak boleh kosong");
                            return;
             }
             if(txtNmBarang.getText().length()==0) {
                             JOptionPane.showMessageDialog(this, "data tidak boleh kosong");
                             return;
             }
             if(txtHrgBarang.getText().length()==0){
                             JOptionPane.showMessageDialog(this, "data tidak boleh kosong");
                             return;
                         }
          Barang barang = new Barang(txtKdBarang.getText(), txtNmBarang.getText(), new BigDecimal(txtHrgBarang.getText()));
                            barangDao.save(barang);
                            tableModel = new BaseTableModel<Barang>() {};
                            tblBrg.setModel(tableModel);
                            barangDao = BarangDao.getBarangDao();
                            List<Barang> listBarang = barangDao.getAll();
                            tableModel.setItem(listBarang);
                            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
                            txtKdBarang.setText("");
                            txtNmBarang.setText("");
                            txtHrgBarang.setText("");
                         
       } catch (HeadlessException e) {
           JOptionPane.showMessageDialog(this, "Data gagal disimpan");
       } catch (SQLException ex) {
            Logger.getLogger(BarangUi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jSimpanActionPerformed

    private void jEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditActionPerformed
        
        if (tblBrg.getSelectedRow() != -1) {
			
			if(txtKdBarang.getText().length()==0){
				JOptionPane.showMessageDialog(this, "Id Masih kosong");
				return;
			}
			if(txtNmBarang.getText().length()==0){
				JOptionPane.showMessageDialog(this, "Nama Masih kosong");
				return;
			}
			if(txtHrgBarang.getText().length()==0){
				JOptionPane.showMessageDialog(this, "Alamat Masih kosong");
				return;
			}
			
			Barang barang = new Barang((txtKdBarang.getText()), txtNmBarang.getText(), new BigDecimal(txtHrgBarang.getText()));
			try {
				barangDao.update(barang);
				tableModel.setItem(barangDao.getAll());
				JOptionPane.showMessageDialog(this, "Data Berhasil diperbarui");
				txtKdBarang.setText("");
				txtNmBarang.setText("");
				txtHrgBarang.setText("");
			} catch (SQLException e) {
				JOptionPane.showMessageDialog(this, e.getMessage());
			}
		}else {
			JOptionPane.showMessageDialog(this, "Pilih data dulu");
		}
        
    }//GEN-LAST:event_jEditActionPerformed

    private void tblBrgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBrgMouseClicked
        
        int row = tblBrg.rowAtPoint(evt.getPoint());
      

       String add1 = tblBrg.getValueAt(row, 0).toString();
       String add2 = tblBrg.getValueAt(row, 1).toString();
       String add3 = tblBrg.getValueAt(row, 2).toString();

        txtKdBarang.setText(add1);
        txtNmBarang.setText(add2);
        txtHrgBarang.setText(add3);
        
        
    }//GEN-LAST:event_tblBrgMouseClicked

    private void jHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHapusActionPerformed
        
        int row = tblBrg.getSelectedRow();
        if (row==-1) {
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu");
        }else{
            Barang barang = new Barang(txtKdBarang.getText(), txtNmBarang.getText(), new BigDecimal(txtHrgBarang.getText()));
            JOptionPane.showConfirmDialog(this,"Yakin Mau Hapus?","Konfirmasi Hapus Data",JOptionPane.YES_NO_OPTION);
            try {
                barangDao.delete(barang);
            } catch (SQLException ex) {
                Logger.getLogger(PelangganUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtKdBarang.setText("");
            txtNmBarang.setText("");
            txtHrgBarang.setText("");
            tableModel = new BaseTableModel<Barang>() {};
                     tblBrg.setModel(tableModel);
                     barangDao = BarangDao.getBarangDao();
                     List<Barang> listBarang = barangDao.getAll();
                     tableModel.setItem(listBarang);
                     JOptionPane.showMessageDialog(this, "Data Berhasil dihapus");
            
        }  
        
    }//GEN-LAST:event_jHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jEdit;
    private javax.swing.JButton jHapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSimpan;
    private javax.swing.JTable tblBrg;
    private javax.swing.JTextField txtHrgBarang;
    private javax.swing.JTextField txtKdBarang;
    private javax.swing.JTextField txtNmBarang;
    // End of variables declaration//GEN-END:variables
}
