/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kreditku.anto.ui;

import com.kreditku.anto.dao.CustomerDao;
import com.kreditku.anto.model.Customer;
import com.mirzaakhena.swing.basetablemodel.BaseTableModel;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author antosamalona
 */
public class PelangganUi extends javax.swing.JInternalFrame {
    
    private CustomerDao customerDao;
    private Customer customer;
    private BaseTableModel<Customer> tableModel;  

    
   
    
    
    
   
    /**
     * Creates new form PelangganUi
     */
    public PelangganUi() {
        initComponents();
       tableModel = new BaseTableModel<Customer>() {};
            tblPelanggan.setModel(tableModel);
            customerDao = CustomerDao.getCustomerDao();
            List<Customer> listCustomer = customerDao.getAll();
            tableModel.setItem(listCustomer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKodPe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jEdit = new javax.swing.JButton();
        jSimpan = new javax.swing.JButton();
        jHapus = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPelanggan = new javax.swing.JTable();

        setClosable(true);
        setTitle("Data Pelanggan");
        setAutoscrolls(true);
        setName(""); // NOI18N

        jLabel1.setText("Kode Pelanggan");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        jEdit.setText("Edit");
        jEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditActionPerformed(evt);
            }
        });

        jSimpan.setText("Simpan");
        jSimpan.setMaximumSize(new java.awt.Dimension(88, 25));
        jSimpan.setPreferredSize(new java.awt.Dimension(88, 25));
        jSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSimpanActionPerformed(evt);
            }
        });

        jHapus.setText("Hapus");
        jHapus.setMaximumSize(new java.awt.Dimension(88, 25));
        jHapus.setPreferredSize(new java.awt.Dimension(88, 25));
        jHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHapusActionPerformed(evt);
            }
        });

        tblPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPelangganMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPelanggan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKodPe, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKodPe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEdit))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSimpanActionPerformed
        
        try {
            
            //KoneksiDb.connection.setAutoCommit(false);
            customerDao = CustomerDao.getCustomerDao();
            Customer customer = new Customer(title, title, title);
            customer.setKd_pelanggan(txtKodPe.getText());
            customer.setNama(txtNama.getText());
            customer.setAlamat(txtAlamat.getText());
             if(txtKodPe.getText().length()==0){
                            JOptionPane.showMessageDialog(this, "data tidak boleh kosong");
                         }else if(txtNama.getText().length()==0) {
                             JOptionPane.showMessageDialog(this, "data tidak boleh kosong");
                         }else if(txtAlamat.getText().length()==0){
                             JOptionPane.showMessageDialog(this, "data tidak boleh kosong");
                         }else{
          
                            customerDao.save(customer);
                            tableModel = new BaseTableModel<Customer>() {};
                            tblPelanggan.setModel(tableModel);
                            customerDao = CustomerDao.getCustomerDao();
                            List<Customer> listCustomer = customerDao.getAll();
                            tableModel.setItem(listCustomer);
                            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
                            txtKodPe.setText("");
                            txtNama.setText("");
                            txtAlamat.setText("");
                         }
       } catch (HeadlessException e) {
           JOptionPane.showMessageDialog(this, "Data gagal disimpan");
       } catch (SQLException ex) {
            Logger.getLogger(PelangganUi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jSimpanActionPerformed
    
    private void jEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditActionPerformed
        int row = tblPelanggan.getSelectedRow();
        if (row==-1) {
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu");
        }else{
        
            Customer customer = new Customer(title, title, title);
            customer.setKd_pelanggan(txtKodPe.getText());
            customer.setNama(txtNama.getText());
            customer.setAlamat(txtAlamat.getText());
            try {
                customerDao.update(customer);
            } catch (SQLException ex) {
                Logger.getLogger(PelangganUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            tableModel = new BaseTableModel<Customer>() {};
                     tblPelanggan.setModel(tableModel);
                     customerDao = CustomerDao.getCustomerDao();
                     List<Customer> listCustomer = customerDao.getAll();
                     tableModel.setItem(listCustomer);
                     JOptionPane.showMessageDialog(this, "Data Berhasil diperbarui");
        
        }
    }//GEN-LAST:event_jEditActionPerformed

    private void tblPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPelangganMouseClicked
        
        int row = tblPelanggan.rowAtPoint(evt.getPoint());
      

       String add1 = tblPelanggan.getValueAt(row, 0).toString();
       String add2 = tblPelanggan.getValueAt(row, 1).toString();
       String add3 = tblPelanggan.getValueAt(row, 2).toString();

        txtKodPe.setText(add1);
        txtNama.setText(add2);
        txtAlamat.setText(add3);
        
    }//GEN-LAST:event_tblPelangganMouseClicked

    private void jHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHapusActionPerformed
        
        int row = tblPelanggan.getSelectedRow();
        if (row==-1) {
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu");
        }else{
            Customer customer = new Customer(title, title, title);
            customer.setKd_pelanggan(txtKodPe.getText());
            customer.setNama(txtNama.getText());
            customer.setAlamat(txtAlamat.getText());
            JOptionPane.showConfirmDialog(this,"Yakin Mau Hapus?","Konfirmasi Hapus Data",JOptionPane.YES_NO_OPTION);
            try {
                customerDao.delete(customer);
            } catch (SQLException ex) {
                Logger.getLogger(PelangganUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtKodPe.setText("");
            txtNama.setText("");
            txtAlamat.setText("");
            tableModel = new BaseTableModel<Customer>() {};
                     tblPelanggan.setModel(tableModel);
                     customerDao = CustomerDao.getCustomerDao();
                     List<Customer> listCustomer = customerDao.getAll();
                     tableModel.setItem(listCustomer);
                     JOptionPane.showMessageDialog(this, "Data Berhasil dihapus");
            
        }  
    }//GEN-LAST:event_jHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jEdit;
    private javax.swing.JButton jHapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jSimpan;
    private javax.swing.JTable tblPelanggan;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtKodPe;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
